package com.example.burungkurirapp.ui.constant.types

data class Transaksi(
    val id: Long,
    val idPengguna: Long,
    val idSeller: Int,
    val idBarangInduk: Long,
    val idKategoriBarang: Long,
    val idAlamatPengguna: Long,
    val gambarUrlKategoriBarang: List<String>,
    val alamatPengguna: AlamatPengguna,
    val idAlamatGudang: Long,
    val alamatGudang: AlamatGudang,
    val idAlamatEkspedisi: Long,
    val idPembayaran: Long,
    val idDiskon: Long?,
    val kendaraanPengiriman: String,
    val jenisPengiriman: String,
    val jarakTempuh: String,
    val beratTotalKg: Short,
    val kodeOrderSistem: String,
    val kodeResiEkspedisi: String,
    val status: String,
    val dibatalkanOleh: String,
    val catatan: String,
    val kuantitasBarang: Int,
    val isEkspedisi: Boolean,
    val sellerPaid: Long,
    val kurirPaid: Long,
    val sistemPaid: Long,
    val ekspedisiPaid: Long,
    val total: Long,
    val reviewed: Boolean,
    val createdAt: String,
    val updatedAt: String,
)